config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  
  resources :information, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :services, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :groups, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :categories, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end
  
  resources :environments, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  devise_for :users

  # dev用メール
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/information.rb
class Information < ApplicationRecord
  VALID_PHONE_REGEX = /\A(\d|-){10,11}\z/
  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/

  validates :name, :server_name, presence:true
  validates :hard_contact_tel, format: { with: VALID_PHONE_REGEX }, if: -> { not hard_contact_tel.blank? }
  validates :soft_contact_tel, format: { with: VALID_PHONE_REGEX }, if: -> { not soft_contact_tel.blank? }
  validates :sales_contact_tel, format: { with: VALID_PHONE_REGEX }, if: -> { not sales_contact_tel.blank? }
  validates :hard_contact_mail, format: { with: VALID_EMAIL_REGEX }, if: -> { not hard_contact_mail.blank? }
  validates :soft_contact_mail, format: { with: VALID_EMAIL_REGEX }, if: -> { not soft_contact_mail.blank? }
  validates :sales_contact_mail, format: { with: VALID_EMAIL_REGEX }, if: -> { not sales_contact_mail.blank? }
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  def index
    @information = Information.all
  end

  def show
    #@comment = @blog.comments.build
    #@comments = @blog.comments
    #Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    if params[:back]
      @information = Information.new(information_params)
    else
      @information = Information.new
    end
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      redirect_to information_index_path, notice: "登録完了"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @information.update(information_params)
      redirect_to information_index_path, notice: "更新完了"
    else
      render 'edit'
    end
  end

  def confirm
    @information = Information.new(information_params)
    render :new if @information.invalid?
  end

  def destroy
    @information.destroy
    redirect_to information_index_path, notice: "削除完了"
  end

  private
    def information_params
      params.require(:information).permit(:group, :service, :category, :environment, :name, :serial, :server_name, :support_contact, :support_contact_period, :support_id, :hard_support_conditions, :hard_contact_tel, :hard_contact_mail, :hard_contact_other, :soft_support_conditions, :soft_contact_tel, :soft_contact_mail, :soft_contact_other, :os_version, :eos_hard, :eos_soft, :sales_contact, :sales_contact_tel, :sales_contact_mail, :remarks_1, :remarks_2, :remarks_3, :non_alert_flag)
    end

    def set_information
      @information = Information.find(params[:id])
    end
end

app/helpers/information_helper.rb
module InformationHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_information_index_path
    elsif action_name == 'edit'
      information_path
    end
  end
end

app/views/information/_form.html.erb
<%= form_for(@information, url: choose_new_or_edit) do |f| %>

  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= @information.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @information.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "サービスID" %>
  <%= f.collection_select :service, Service.all, :id, :name, :include_blank => true %>
  <br>
  <%= f.label :name, "グループID" %>
  <%= f.collection_select :group, Group.all, :id, :name, :include_blank => true %>
  <br>
  <%= f.label :name, "機種別ID" %>
  <%= f.collection_select :category, Category.all, :id, :name, :include_blank => true %>
  <br>
  <%= f.label :name, "環境ID" %>
  <%= f.collection_select :environment, Environment.all, :id, :name, :include_blank => true %>
  <br>
  <%= f.label :name, "機器名" %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>
  <%= f.label :name, "シリアルナンバー" %>
  <%= f.text_field :serial, class: 'form-control' %>
  <br>
  <%= f.label :name, "サーバー名" %>
  <%= f.text_field :server_name, class: 'form-control' %>
  <br>
  <%= f.label :name, "保守ベンダー" %>
  <%= f.text_field :support_contact, class: 'form-control' %>
  <br>
  <%= f.label :name, "保守契約期間" %>
  <%= f.date_field :support_contact_period, class: 'form-control' %>
  <br>
  <%= f.label :name, "保守番号" %>
  <%= f.text_field :support_id, class: 'form-control' %>
  <br>
  <%= f.label :name, "ハード保守条件" %>
  <%= f.text_field :hard_support_conditions, class: 'form-control' %>
  <br>
  <%= f.label :name, "ハード保守電話番号" %>
    (半角数字 + 半角ハイフンでご入力ください)
  <%= f.telephone_field :hard_contact_tel, class: 'form-control' %>
  <br>
  <%= f.label :name, "ハード保守メールアドレス" %>
  <%= f.email_field :hard_contact_mail, class: 'form-control' %>
  <br>
  <%= f.label :name, "ハード保守その他" %>
  <%= f.text_field :hard_contact_other, class: 'form-control' %>
  <br>
  <%= f.label :name, "ソフト保守条件" %>
  <%= f.text_field :soft_support_conditions, class: 'form-control' %>
  <br>
  <%= f.label :name, "ソフト保守電話番号" %>
    (半角数字 + 半角ハイフンでご入力ください)
  <%= f.telephone_field :soft_contact_tel, class: 'form-control' %>
  <br>
  <%= f.label :name, "ソフト保守メールアドレス" %>
  <%= f.email_field :soft_contact_mail, class: 'form-control' %>
  <br>
  <%= f.label :name, "ソフト保守その他" %>
  <%= f.text_field :soft_contact_other, class: 'form-control' %>
  <br>
  <%= f.label :name, "OSバージョン" %>
  <%= f.text_field :os_version, class: 'form-control' %>
  <br>
  <%= f.label :name, "ハード保守期限" %>
  <%= f.date_field :eos_hard, class: 'form-control' %>
  <br>
  <%= f.label :name, "ソフト保守期限" %>
  <%= f.date_field :eos_soft, class: 'form-control' %>
  <br>
  <%= f.label :name, "営業担当者" %>
  <%= f.text_field :sales_contact, class: 'form-control' %>
  <br>
  <%= f.label :name, "営業電話番号" %>
    (半角数字 + 半角ハイフンでご入力ください)
  <%= f.telephone_field :sales_contact_tel, class: 'form-control' %>
  <br>
  <%= f.label :name, "営業メールアドレス" %>
  <%= f.email_field :sales_contact_mail, class: 'form-control' %>
  <br>
  <%= f.label :name, "備考1" %>
  <%= f.text_field :remarks_1, class: 'form-control' %>
  <br>
  <%= f.label :name, "備考2" %>
  <%= f.text_field :remarks_2, class: 'form-control' %>
  <br>
  <%= f.label :name, "備考3" %>
  <%= f.text_field :remarks_3, class: 'form-control' %>
  <br>
  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/information/confirm.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">

    <h3>内容確認</h3>

    <%= form_for(@information) do |f| %>
      <%= f.hidden_field :service %>
      <%= f.hidden_field :group %>
      <%= f.hidden_field :category %>
      <%= f.hidden_field :environment %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :serial %>
      <%= f.hidden_field :server_name %>
      <%= f.hidden_field :support_contact %>
      <%= f.hidden_field :support_contact_period %>
      <%= f.hidden_field :support_id %>
      <%= f.hidden_field :hard_support_conditions %>
      <%= f.hidden_field :hard_contact_tel %>
      <%= f.hidden_field :hard_contact_mail %>
      <%= f.hidden_field :hard_contact_other %>
      <%= f.hidden_field :soft_support_conditions %>
      <%= f.hidden_field :soft_contact_tel %>
      <%= f.hidden_field :soft_contact_mail %>
      <%= f.hidden_field :soft_contact_other %>
      <%= f.hidden_field :os_version %>
      <%= f.hidden_field :eos_hard %>
      <%= f.hidden_field :eos_soft %>
      <%= f.hidden_field :sales_contact %>
      <%= f.hidden_field :sales_contact_tel %>
      <%= f.hidden_field :sales_contact_mail %>
      <%= f.hidden_field :remarks_1 %>
      <%= f.hidden_field :remarks_2 %>
      <%= f.hidden_field :remarks_3 %>

      <p>サービス:<%= @information.service %></p>
      <p>グループ:<%= @information.group %></p>
      <p>機種別:<%= @information.category %></p>
      <p>環境:<%= @information.environment %></p>
      <p>機器名:<%= @information.name %></p>
      <p>シリアルナンバー:<%= @information.serial %></p>
      <p>サーバー名:<%= @information.server_name %></p>
      <p>保守ベンダー:<%= @information.support_contact %></p>
      <p>保守契約期間:<%= @information.support_contact_period %></p>
      <p>保守番号:<%= @information.support_id %></p>
      <p>ハード保守条件:<%= @information.hard_support_conditions %></p>
      <p>ハード保守電話番号:<%= @information.hard_contact_tel %></p>
      <p>ハード保守メールアドレス:<%= @information.hard_contact_mail %></p>
      <p>ハード保守その他:<%= @information.hard_contact_other %></p>
      <p>ソフト保守条件:<%= @information.soft_support_conditions %></p>
      <p>ソフト保守電話番号:<%= @information.soft_contact_tel %></p>
      <p>ソフト保守メールアドレス:<%= @information.soft_contact_mail %></p>
      <p>ソフト保守その他:<%= @information.soft_contact_other %></p>
      <p>OSバージョン:<%= @information.os_version %></p>
      <p>ハード保守期限:<%= @information.eos_hard %></p>
      <p>ソフト保守期限:<%= @information.eos_soft %></p>
      <p>営業担当者:<%= @information.sales_contact %></p>
      <p>営業電話番号:<%= @information.sales_contact_tel %></p>
      <p>営業メールアドレス:<%= @information.sales_contact_mail %></p>
      <p>備考1:<%= @information.remarks_1 %></p>
      <p>備考2:<%= @information.remarks_2 %></p>
      <p>備考3:<%= @information.remarks_3 %></p>

      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@information, url: new_information_path, method: 'get') do |f| %>
      <%= f.hidden_field :service %>
      <%= f.hidden_field :group %>
      <%= f.hidden_field :category %>
      <%= f.hidden_field :environment %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :serial %>
      <%= f.hidden_field :server_name %>
      <%= f.hidden_field :support_contact %>
      <%= f.hidden_field :support_contact_period %>
      <%= f.hidden_field :support_id %>
      <%= f.hidden_field :hard_support_conditions %>
      <%= f.hidden_field :hard_contact_tel %>
      <%= f.hidden_field :hard_contact_mail %>
      <%= f.hidden_field :hard_contact_other %>
      <%= f.hidden_field :soft_support_conditions %>
      <%= f.hidden_field :soft_contact_tel %>
      <%= f.hidden_field :soft_contact_mail %>
      <%= f.hidden_field :soft_contact_other %>
      <%= f.hidden_field :os_version %>
      <%= f.hidden_field :eos_hard %>
      <%= f.hidden_field :eos_soft %>
      <%= f.hidden_field :sales_contact %>
      <%= f.hidden_field :sales_contact_tel %>
      <%= f.hidden_field :sales_contact_mail %>
      <%= f.hidden_field :remarks_1 %>
      <%= f.hidden_field :remarks_2 %>
      <%= f.hidden_field :remarks_3 %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>

  </div>
</div>

app/views/information/edit.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/information/index.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-12">

      <p><%= notice %></p>
      <h1>登録情報一覧</h1>

      <p>
        <%= link_to "追加", new_information_path, class: 'btn btn-default' %>
      </p>

      <div class="alt-table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>No.</th>
              <th>サービスID</th>
              <th>グループID</th>
              <th>機種別ID</th>
              <th>環境ID</th>
              <th>機器名</th>
              <th>シリアルナンバー</th>
              <th>サーバー名</th>
              <th>保守ベンダー</th>
              <th>保守契約期間</th>
              <th>保守番号</th>
              <th>ハード保守条件</th>
              <th>ハード保守電話番号</th>
              <th>ハード保守メールアドレス</th>
              <th>ハード保守その他</th>
              <th>ソフト保守条件</th>
              <th>ソフト保守電話番号</th>
              <th>ソフト保守メールアドレス</th>
              <th>ソフト保守その他</th>
              <th>OSバージョン</th>
              <th>ハード保守期限</th>
              <th>ソフト保守期限</th>
              <th>営業担当者</th>
              <th>営業電話番号</th>
              <th>営業メールアドレス</th>
              <th>備考1</th>
              <th>備考2</th>
              <th>備考3</th>
              <th>保守期限アラート無効</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <% @information.each do |info| %>
              <tr>
                <th><%= info.id %></th>
                <td>
                  <% if (info.service.blank?) %>
                    <%= info.service %>
                  <% else %>
                    <%= Service.find(info.service).name %>
                  <% end %>
                </td>
                <td>
                  <% if (info.group.blank?) %>
                    <%= info.group %>
                  <% else %>
                    <%= Group.find(info.group).name %>
                  <% end %>
                </td>
                <td>
                  <% if (info.category.blank?) %>
                    <%= info.category %>
                  <% else %>
                    <%= Category.find(info.category).name %>
                  <% end %>
                </td>
                <td>
                  <% if (info.environment.blank?) %>
                    <%= info.environment %>
                  <% else %>
                    <%= Environment.find(info.environment).name %>
                  <% end %>
                </td>
                <td><%= info.name %></td>
                <td><%= info.serial %></td>
                <td><%= info.server_name %></td>
                <td><%= info.support_contact %></td>
                <td><%= info.support_contact_period %></td>
                <td><%= info.support_id %></td>
                <td><%= info.hard_support_conditions %></td>
                <td><%= info.hard_contact_tel %></td>
                <td><%= info.hard_contact_mail %></td>
                <td><%= info.hard_contact_other %></td>
                <td><%= info.soft_support_conditions %></td>
                <td><%= info.soft_contact_tel %></td>
                <td><%= info.soft_contact_mail %></td>
                <td><%= info.soft_contact_other %></td>
                <td><%= info.os_version %></td>
                <td><%= info.eos_hard %></td>
                <td><%= info.eos_soft %></td>
                <td><%= info.sales_contact %></td>
                <td><%= info.sales_contact_tel %></td>
                <td><%= info.sales_contact_mail %></td>
                <td><%= info.remarks_1 %></td>
                <td><%= info.remarks_2 %></td>
                <td><%= info.remarks_3 %></td>
                <td><%= info.non_alert_flag %></td>
                <td>
                  <%= link_to "編集", edit_information_path(info.id), class: 'btn btn-default btn-sm btn-success' %>
                  <%= link_to "削除", information_path(info.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <%= link_to "サービス一覧", services_path, class: 'btn btn-default' %>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <%= link_to "グループ一覧", groups_path, class: 'btn btn-default' %>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <%= link_to "カテゴリ一覧", categories_path, class: 'btn btn-default' %>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-1@">
          <%= link_to "環境一覧", environments_path, class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/information/new.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>追加する</h2>
    <%= render 'form' %>
  </div>
</div>