config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  
  resources :information, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :services, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :groups, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :categories, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end
  
  resources :environments, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  devise_for :users

  # dev用メール
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :information, primary_key: "name", foreign_key: "group", class_name: "Information"
  
  validates :name, presence:true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_groups, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    #@comment = @blog.comments.build
    #@comments = @blog.comments
    #Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    if params[:back]
      @groups = Group.new(groups_params)
    else
      @groups = Group.new
    end
  end

  def create
    @groups = Group.new(groups_params)
    if @groups.save
      redirect_to groups_path, notice: "登録完了"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @groups.update(groups_params)
      redirect_to groups_path, notice: "更新完了"
    else
      render 'edit'
    end
  end

  def confirm
    @groups = Group.new(groups_params)
    render :new if @groups.invalid?
  end

  def destroy
    @groups.destroy
    redirect_to groups_path, notice: "削除完了"
  end

  private
    def groups_params
      params.require(:group).permit(:name)
    end

    def set_groups
      @groups = Group.find(params[:id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_groups_path
    elsif action_name == 'edit'
      group_path
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for(@groups, url: group_choose_new_or_edit) do |f| %>

  <% if @groups.errors.any? %>
    <div id="error_explanation">
      <h2><%= @groups.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @groups.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "グループ名" %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>
  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/groups/confirm.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">

    <h3>内容確認</h3>

    <%= form_for(@groups) do |f| %>
      <%= f.hidden_field :name %>

      <p>グループ名:<%= @groups.name %></p>

      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@groups, url: new_group_path, method: 'get') do |f| %>
      <%= f.hidden_field :name %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>

  </div>
</div>

app/views/groups/edit.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
  <div class="wrapper col-md-12 col-sm-10">

    <p><%= notice %></p>
    <h1>グループ一覧</h1>

    <p>
      <%= link_to "追加", new_group_path, class: 'btn btn-default' %>
    </p>

    <div class="table-responsive">
      <table class="table table-striped 
      table-bordered table-hover">
        <thead>
          <tr>
            <th>No.</th>
            <th>グループ</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <th><%= group.id %></th>
              <td><%= group.name %></td>
              <td>
                <%= link_to "編集", edit_group_path(group.id), class: 'btn btn-default btn-sm btn-success' %>
                <%= link_to "削除", group_path(group.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
    </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>追加する</h2>
    <%= render 'form' %>
  </div>
</div>