config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  
  resources :information, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :services, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :groups, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  resources :categories, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end
  
  resources :environments, only: [:index, :new, :create, :destroy, :edit, :update] do
    post :confirm, on: :collection
  end

  devise_for :users

  # dev用メール
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/environment.rb
class Environment < ApplicationRecord
  has_many :information, primary_key: "name", foreign_key: "environment", class_name: "Information"
  
  validates :name, presence:true
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_environments, only: [:show, :edit, :update, :destroy]

  def index
    @environments = Environment.all
  end

  def show
    #@comment = @blog.comments.build
    #@comments = @blog.comments
    #Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    if params[:back]
      @environments = Environment.new(environments_params)
    else
      @environments = Environment.new
    end
  end

  def create
    @environments = Environment.new(environments_params)
    if @environments.save
      redirect_to environments_path, notice: "登録完了"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @environments.update(environments_params)
      redirect_to environments_path, notice: "更新完了"
    else
      render 'edit'
    end
  end

  def confirm
    @environments = Environment.new(environments_params)
    render :new if @environments.invalid?
  end

  def destroy
    @environments.destroy
    redirect_to environments_path, notice: "削除完了"
  end

  private
    def environments_params
      params.require(:environment).permit(:name)
    end

    def set_environments
      @environments = Environment.find(params[:id])
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
  def environment_choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_environments_path
    elsif action_name == 'edit'
      environment_path
    end
  end
end

app/views/environments/_form.html.erb
<%= form_for(@environments, url: environment_choose_new_or_edit) do |f| %>

  <% if @environments.errors.any? %>
    <div id="error_explanation">
      <h2><%= @environments.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @environments.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "環境名" %>
  <%= f.text_field :name, class: 'form-control' %>
  <br>
  <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/environments/confirm.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">

    <h3>内容確認</h3>

    <%= form_for(@environments) do |f| %>
      <%= f.hidden_field :name %>

      <p>環境名:<%= @environments.name %></p>

      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@environments, url: new_environment_path, method: 'get') do |f| %>
      <%= f.hidden_field :name %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>

  </div>
</div>

app/views/environments/edit.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/environments/index.html.erb
<div class="container">
  <div class="row">
  <div class="wrapper col-md-12 col-sm-10">

    <p><%= notice %></p>
    <h1>環境一覧</h1>

    <p>
      <%= link_to "追加", new_environment_path, class: 'btn btn-default' %>
    </p>

    <div class="table-responsive">
      <table class="table table-striped 
      table-bordered table-hover">
        <thead>
          <tr>
            <th>No.</th>
            <th>環境</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @environments.each do |environment| %>
            <tr>
              <th><%= environment.id %></th>
              <td><%= environment.name %></td>
              <td>
                <%= link_to "編集", edit_environment_path(environment.id), class: 'btn btn-default btn-sm btn-success' %>
                <%= link_to "削除", environment_path(environment.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
    </div>
</div>

app/views/environments/new.html.erb
<div class="container">
  <div class="col-md-12 col-sm-10">
    <h2>追加する</h2>
    <%= render 'form' %>
  </div>
</div>